- .yarnrc.yml
- src/utils/index.ts
- src/views/overview/components/CollateralPieChart.tsx
- yarn.lock
Noticed a few quick fixes:
1. `yarn install` currently fails without the checksum option I've added
2. Added z-index to the tooltip wrapper
3. Added percentage formatter to tooltip values
> Stylistic fixes for CollateralPieChart

- src/components/transaction-input/index.tsx
- src/state/atoms.ts
- src/state/rtoken/RTokenStateUpdater.tsx
- src/types/index.ts
- src/views/issuance/components/issue/IssueInput.tsx
- src/views/issuance/components/redeem/RedeemInput.tsx
Add maximum issuance and redemption numbers to the UI along with a tooltip explaining these numbers
> feat: add max issuance/redemption throttle amounts

- src/components/rtoken-setup/atoms.ts
- src/utils/plugins/mainnet.ts
- src/views/governance/components/ProposalDetailPreview.tsx
- src/views/governance/views/proposal/hooks/useProposalTx.ts
- src/views/governance/views/proposal/updater.tsx
This error was reported by a user when trying to switch eUSD basket  
> I tried building a primary basket proposal using Register today, and thanks to all that you've taught me, I spotted a few errors in what it generated -- it used register instead of swapRegistered with the Asset Registry even though there are already collateral plugins registered for cUSDC and saUSDC (which i was putting in the basket), and this one I'm guessing is wrong, it built the array of assets for setPrimeBasket using the collateral plug-in addresses instead of the erc20 contract addresses.
This is corrected by checking whether the underlying asset had already been registered, and if so, call swapRegistered.
> Use swapRegistered for collateral when appropriate

- src/views/governance/components/AccountVotes.tsx
- src/views/governance/views/proposal-detail/components/ProposalVote.tsx
Closes #52 
3 different states are now represented by a single button
1. When user has no voting power available  
2. User has undelegated voting power (same conditions for showing the former "Please delegate your voting power" message). Clicking the button will show the `DelegateModal`.
- After delegating, the user will see the screen in 1) above because it is either past the proposal snapshot or they're on a proposal for which voting hasn't started yet
3. User has active voting power for this proposal - this is unchanged from before
> Feat: consolidate voting/delegation into single button

- .env.example
- .github/workflows/guardian.yml
- .gitignore
- README.md
- package.json
- playwright.config.ts
- src/hooks/useTransactionCost.ts
- src/views/issuance/components/issue/ConvexCollateralModal.tsx
- src/views/issuance/components/issue/WrapCollateralModal.tsx
- tests/AAVEWrapper.gui.ts
- tests/ConvexStakingWrapper.gui.ts
- tests/RTokens.gui.ts
- tests/getRTokens.ts
- tests/utils.ts
- tsconfig.json
- yarn.lock
[Register.app](http://register.app/) is the user-interface for the Reserve Protocol. It was built to allow users to deploy, view, use, and govern RTokens, and is currently doing its job well. There are currently no tests in the Register codebase. 
The goal of this badge is to setup an E2E testing framework that can be run locally and in github actions CI. [GuardianUI](https://www.guardianui.com/) should be used as the testing framework. 
- I found some minor bugs in the approvals. `contract.estimateGas[tx.call.method]()` doesn't work with other rpc such as anvil or alchemy, but i've replaced with `contract.signer.estimateGas` to work for all rpcs
> feat: add e2e test

- src/views/governance/components/GovernanceOverview.tsx
It is technically possible to have multiple owners of an RToken (capable of upgrading contracts, etc). This PR lists all of addresses with that role under the Governance tab
> chore: add owners to governance view

- src/views/overview/components/PriceChart.tsx
- src/views/overview/components/StakingChart.tsx
- src/views/overview/components/SupplyChart.tsx
- src/views/staking/components/overview/ExchangeRate.tsx
Previously, charts on the 1yr timescale would display truncated results because TheGraph fetches a max of 100 results by default. Now, we fetch the first 1000 to overcome this. 
Affects the follow charts: 
- RSR price 
- RToken price
- RToken supply
- RSR staked
> fix: override default Graph results limit

- package-lock.json
- package.json
A lot of reverts are happening because rates might change from the time a user submits a zap to when it actually gets committed on chain. I made the internal quoting in the zapper a bit more pessimistic, which should allow zap transactions to stay valid for up to 20 minutes even if the rate spikes to 10%+.
> update zapper to better handle on-chain rates appreciating over time

- src/components/rtoken-setup/basket/UnitBasket.tsx
Shows the actual collateral address when changing basket. Useful for when you're changing the collateral address with the same token symbols.
> Display Collateral Address

- src/components/rtoken-setup/atoms.ts
- src/components/rtoken-setup/token/RevenueSplit.tsx
- src/state/rtoken/atoms/rTokenBackupAtom.ts
- src/views/governance/views/proposal/atoms.ts
- src/views/governance/views/proposal/components/ProposalForm.tsx
- src/views/governance/views/proposal/components/ProposalPreview.tsx
- src/views/governance/views/proposal/components/ProposedRegisterPreview.tsx
- src/views/governance/views/proposal/components/ProposedUnregisterPreview.tsx
- src/views/governance/views/proposal/components/RegisterEdit.tsx
- src/views/governance/views/proposal/components/RegisterProposal.tsx
- src/views/governance/views/proposal/components/UnregisterEdit.tsx
- src/views/governance/views/proposal/components/UnregisterProposal.tsx
- src/views/governance/views/proposal/hooks/useProposalTx.ts
- src/views/governance/views/proposal/hooks/useRegisterAssets.ts
- src/views/governance/views/proposal/updater.tsx
Caveat is that this list will in inaccurate for RTokens that have not upgraded to the most recent version (and thus their assets will not be present in the `mainnet.json` mainfest)
> Unregister unused assets

- src/views/governance/views/proposal/hooks/useProposalTx.ts
Previously, numerical parameter changes weren't being parsed correctly, leading to such errors, which this PR fixes:
> Parse governance change params

- src/views/governance/views/proposal/hooks/useProposalTx.ts
In the original code, `newBackup` was mistakenly used and it's a boolean, which is not suitable for `Object.keys()`. Changing it to `backup`, which is an object, fixed the issue, allowing the proposal to correctly process changes in the emergency basket.
> Bug Fix: track emergency basket changes for a new proposal

- src/components/rtoken-setup/token/ExternalRevenueSplit.tsx
> Bugfix: fix revenue fields in the deployment form

- src/views/governance/components/ProposalList.tsx
- src/views/governance/views/proposal-detail/atom.ts
- src/views/governance/views/proposal-detail/components/ProposalCancel.tsx
- src/views/governance/views/proposal-detail/components/ProposalExecute.tsx
- src/views/governance/views/proposal-detail/index.tsx
- Guardian has the ability to cancel a queued tx in the timelock
- Any proposal that has been “canceled” should reflect that in the UI
Changes in the subgraph: https://github.com/reserve-protocol/reserve-subgraph/pull/5
> Feature: Guardian functionality

- src/views/staking/Updater.tsx
- src/views/staking/atoms.ts
On Base hyUSD, because RSR was seized, the `draftEra` in stRSR was incremented.  `FacadeRead` relies on `era`, which results in users not being able to see their pending RSR withdrawals. This is a minor protocol bug.
The solution for now is to manually query the storage slot of `draftEra` so that it can continue to function, until 3.2.0 is released with a `FacadeRead` that corrects this, **at which point this patch should be removed**
See left (with patch) vs right (production) 
Tested with impersonated wallets having pending withdrawals on hyUSD (Base), eUSD, USDC+
> Manually set era on hyusd (base) so withdrawal cooldowns are shown

- package-lock.json
- package.json
This PR fixes a bug in the zapper that caused instability in production.
The bug was caused by the zapper searching both zap by issueance and zap by trade. Expected behavior was for zap to be returned as long as one of them produced a result. But the bug caused the zapper to always recalculate both paths even if there is no way to trade into an RToken.
> Zapper bugfixes round 2

- src/abis/FacadeRead.ts
- src/utils/addresses.ts
- src/views/staking/Updater.tsx
- src/views/staking/atoms.ts
- src/views/staking/components/balances/PendingBalance.tsx
Queries storage slot (again) to get `draftEra`
Also, fixes reducer to only update the `index` for withdrawals if they're passed cooldown. This bug was previously making it so that cooled down stakes couldn't be withdrawn.
> Conform to Facade Read Interface

- package-lock.json
- package.json
- src/views/issuance/components/zap/state/atoms.ts
- src/views/issuance/components/zap/state/ui-atoms.ts
- src/views/issuance/components/zap/state/zapper.ts
Some slippage related code in the UI broke if the zappper was unable to price a token. This was an issue as the zapper was unable to price the curve LP tokens in the hyUSD basket.
This PR contains a fix for the zapper that makes it able to price hyUSD again. It also fixes makes the fixes makes the UI not lock up if the input or output tokens can not be priced.
> fix hyUSD zapping issues

- src/views/issuance/components/zap/state/atoms.ts
Default slippage is now 0.1 bps (1/100000n), previously it was essentially 0
> fix: default zaps to slightly higher slippage

- src/hooks/useTokenList.tsx
Implements the fix to the problem described here https://github.com/reserve-protocol/reserve-subgraph/pull/7
> Use rToken.rsrLocked property for staking APY

- src/views/home/components/RTokenCard.tsx
> Fix: rtoken card alignment

- src/views/overview/components/charts/PriceChart.tsx
> Fix: temporal fix for USDC+ historical price data

- src/utils/constants.ts
- src/views/earn/hooks/useRTokenPools.ts
Added new underlying tokens to Register to track these tokens:
Volatile AMM - hyUSD/eUSD: 0xb5E331615FdbA7DF49e05CdEACEb14Acdd5091c3
Stable AMM - eUSD/USDbC: 0x5BfB340FA9305abB164Fb0248D0D82FC3D82C3bb
> chore: add earn pools

- src/views/issuance/components/zapV2/overview/ZapDetails.tsx
Yes I know what you're thinking: this guy must be airdrop farming with his low hanging fixes! But no, this is a genuine user reporting a typo in the new Zap In interface on the Reserve website that was bothering me ;) 
Example:
> Fix user facing typo in the new zap interface (ZapDetails.tsx)

- src/views/deploy/components/TokenParameters.tsx
- src/views/governance/components/AccountVotes.tsx
- src/views/governance/components/ProposalList.tsx
- src/views/overview/components/backing/BackingBuffer.tsx
- Disabled governance CTAs for RTokens without governance
- Changed backing buffer section title
- Changed chain selection on RToken deployment
- Changed default chain on RToken deployment
> Chore: UI & UX changes

- src/components/rtoken-setup/governance/GovernanceParameters.tsx
This pull request includes changes to the `GovernanceParameters` component in `src/components/rtoken-setup/governance/GovernanceParameters.tsx` to update the time units from seconds to hours for improved clarity.
Updates to time units:
* Modified the `votingDelayHelper`, `votingPeriodHelper`, and `minDelayHelper` to convert the values from seconds to hours. (`src/components/rtoken-setup/governance/GovernanceParameters.tsx`)
* Updated the labels and help text in the `FormField` components to reflect the change from seconds to hours. (`src/components/rtoken-setup/governance/GovernanceParameters.tsx`) [[1]](diffhunk://#diff-e123f135b849d7a659baeaeda4f33e79e75b3de12a5fd691fee86570046f750fL50-R58) [[2]](diffhunk://#diff-e123f135b849d7a659baeaeda4f33e79e75b3de12a5fd691fee86570046f750fL66-R74)
> feat: fix gov display

- src/views/portfolio/rewards-updater.tsx
Get rewards from the simulated call of `claimRewards` which returns the up to date value without needed to interact with the contracts.
> feat: get latest rewards
