reserve-protocol/register

- src/components/field/index.tsx
- src/components/rtoken-setup/basket/PluginItem.tsx
- src/components/rtoken-setup/basket/PrimaryBasket.tsx
- src/components/rtoken-setup/governance/GovernanceParameters.tsx
- src/components/rtoken-setup/token/BackingForm.tsx
- src/components/rtoken-setup/token/OtherForm.tsx
- src/state/atoms.ts
- Add placeholder in inputs for parsing units
- Display estimated apy for primary basket
> feat: improve deployment flow

- src/views/governance/views/proposal-detail/components/ProposalDetailStats.tsx
> feat: add quorum progress bar

- src/views/governance/views/proposal/components/ConfirmProposalForm.tsx
> fix: don't require title before description available

- src/components/transaction-input/index.tsx
- src/utils/plugins/index.ts
- src/views/governance/components/ProposalList.tsx
- src/views/governance/views/proposal/components/Proposal.tsx
- src/views/governance/views/proposal/updater.tsx
- Avoid badge text overflow on proposal list
- Align "Global max" helper on issuance
- Use correct addresses for primary basket proposal **(Temporary fix)**
> Quick fixes

- src/utils/wrapping.ts
- src/views/issuance/components/about/index.tsx
- src/views/issuance/components/issue/UnwrapCollateraModal.tsx
Closes #55 
The new file `UnwrapCollateralModal.tsx` is mostly a copy of `WrapCollateralModal.tsx` and can be discarded when the wrapping interface is re-designed.
> feat: add unwrapping modal

- src/components/rtoken-setup/governance/GovernanceParameters.tsx
- src/components/rtoken-setup/token/BackingForm.tsx
- src/components/rtoken-setup/token/OtherForm.tsx
- src/views/deploy/utils.ts
> Correct parameter defaults and copy on rtoken deployment flow

- package.json
- src/views/issuance/components/zap/state/atoms.ts
- src/views/issuance/components/zap/state/createProxiedOneInchAggregator.ts
- src/views/issuance/components/zap/state/formatTokenQuantity.ts
- src/views/issuance/components/zap/state/ui-atoms.ts
- src/views/issuance/components/zap/state/zapper.ts
- yarn.lock
add some hardening code for 1inch integration.
> hardcode urls for now

- package.json
- src/utils/index.ts
- src/utils/wrapping.ts
- src/views/issuance/components/issue/ConvexCollateralModal.tsx
- src/views/issuance/components/issue/UnwrapCollateraModal.tsx
- src/views/issuance/components/issue/WrapCollateralModal.tsx
- yarn.lock
- Update RTokens, hyUSD added
- Fix rounding issues with the `max` value on the wrapping modals
> Update RToken list and fix wrapping modals

- src/abis/broker.json
- src/views/governance/components/ProposalDetailPreview.tsx
- src/views/governance/views/proposal-detail/components/ProposalDetailStats.tsx
- src/views/governance/views/proposal-detail/components/ProposalExecute.tsx
- src/views/governance/views/proposal-detail/useProposalDetail.ts
- Fix proposal execution promp
- Update broker ABI to 2.1
> Fix proposal execution promp

- src/views/auctions/auctions-sidebar/RevenueAuctionItem.tsx
- src/views/staking/components/balances/Balances.tsx
- I messed up the color of dropdown icons in Auctions making them not appear.
- Trying to improve the understanding of what "USD" is referring to in staking balances.
> Quick fixes for latest CSS changes

- src/components/rtoken-setup/token/BackingForm.tsx
- src/views/deploy/utils.ts
Background here: https://forum.reserve.org/t/rfc-adjust-default-rtoken-throttles/478
> chore: tweak default throttle params

- src/views/home/components/Stats.tsx
> feat: add flipside dashboard link

- src/views/issuance/components/wrapping/atoms.ts
Enable flux wrapping for USDC+
> feat: return wrapping of flux for usdc+

- src/components/chain-selector/ChainSelector.tsx
- src/views/bridge/components/ConfirmBridge.tsx
- src/views/issuance/components/zap/state/atoms.ts
- src/views/issuance/components/zap/state/createProxiedOneInchAggregator.ts
- src/views/issuance/components/zap/state/ui-atoms.ts
- src/views/issuance/components/zap/state/zapper.ts
Specifically tracks zap errors so as to maintain an error log on Mixpanel
> chore: add more mixpanel tracking for zapping errors

- src/components/layout/header/AppHeader.tsx
> add canny to header

- package-lock.json
- package.json
Fixes issue causing the last trade to fail.
> Fix zap hyUSD for USDC base

- src/views/earn/hooks/useRTokenPools.ts
Data from defillama is coming with nulls
> Hotfix: Earn section not loading

- src/components/rtoken-setup/token/OtherForm.tsx
- src/state/rtoken/atoms/rTokenConfigurationAtom.ts
- src/views/governance/components/TopVoters.tsx
- src/views/governance/views/proposal/atoms.ts
- src/views/governance/views/proposal/components/ConfirmProposal.tsx
- src/views/governance/views/proposal/components/ConfirmProposalOverview.tsx
- src/views/governance/views/proposal/components/ContractUpgrades.tsx
- src/views/governance/views/proposal/components/ContractUpgradesPreview.tsx
- src/views/governance/views/proposal/components/ItemPreview.tsx
- src/views/governance/views/proposal/components/ProposalForm.tsx
- src/views/governance/views/proposal/components/ProposalPreview.tsx
- src/views/governance/views/proposal/components/RegisterEdit.tsx
- src/views/governance/views/proposal/components/RegisterProposal.tsx
- src/views/governance/views/proposal/components/SimulateProposal.tsx
- src/views/governance/views/proposal/components/TraderImplementationProposal.tsx
- src/views/governance/views/proposal/hooks/useParametersChanges.ts
- src/views/governance/views/proposal/hooks/useProposalTx.ts
- src/views/governance/views/proposal/updater.tsx
- Support setting trade implementations
- Support upgrading contracts
> Support new governance changes

- src/components/rtoken-setup/basket/CollateralModal.tsx
> Feat: add search bar for collateral modal

- src/components/field/index.tsx
- src/views/governance/views/proposal/components/ConfirmProposalForm.tsx
> Feat: add mandatory RFC field for listed RTokens

- src/components/transactions/table/index.tsx
- src/views/overview/components/RTokenTransactions.tsx
First merge & deploy: https://github.com/reserve-protocol/reserve-subgraph/pull/8
> Fix: change mapping for burn

- src/views/issuance/components/zapV2/context/ZapContext.tsx
- src/views/issuance/components/zapV2/output/ZapOutputUSD.tsx
- src/views/issuance/components/zapV2/submit/ZapSubmitButton.tsx
> Fix: zap price impact

- src/state/updaters/CollateralYieldUpdater.tsx
> Fix: sFRAX APY

- src/views/deploy/components/TokenForm.tsx
- src/views/home/index.tsx
> Chore: disable index RTokens

- package-lock.json
- package.json
- src/components/dgneth/DgnETHButtonAppendix.tsx
- src/views/compare/components/RTokenCard.tsx
- src/views/overview/components/hero/OverviewActions.tsx
> Feat: dgneth link

- src/views/overview/components/charts/PriceChart.tsx
> Feat: Historical price chart in terms of ETH

- src/hooks/useWatchTransaction.ts
- src/views/issuance/components/zapV2/ZapToggleBottom.tsx
- src/views/issuance/components/zapV2/context/ZapContext.tsx
- src/views/issuance/components/zapV2/context/ZapTxContext.tsx
- src/views/issuance/components/zapV2/hooks/useApproval.tsx
- src/views/issuance/index.tsx
- Mixpanel tracking on the Zapper
- Mixpanel transaction tracking
- Improve transaction feedback handling
> Chore: mixpanel tracking & tx feedback handling

- src/hooks/useQuery.ts
- src/state/updaters/CollateralYieldUpdater.tsx
- src/views/overview/components/charts/APYChart.tsx
- src/views/overview/components/charts/index.tsx
- src/views/overview/components/hero/index.tsx
> Feat: historical APY

- src/abis/USDT.ts
- src/components/button/GoTo.tsx
- src/components/layout/header/components/RegisterHelp.tsx
- src/views/issuance/components/issue/CollateralApprovals.tsx
- src/views/issuance/components/wrapping/CollateralItem.tsx
- src/views/issuance/components/zapV2/context/ZapContext.tsx
- src/views/issuance/components/zapV2/context/ZapTxContext.tsx
- src/views/issuance/components/zapV2/hooks/useApproval.tsx
- src/views/issuance/components/zapV2/hooks/useRevokeUSDT.tsx
- src/views/issuance/components/zapV2/submit/ZapConfirm.tsx
- src/views/issuance/components/zapV2/submit/ZapRevokeButton.tsx
- src/views/overview/components/backing/CollateralExposure.tsx
- Using USDT as collateral
- Wrapping USDT
- Using USDT on zap mints
Also included into this PR:
- Let users copy details from RToken Details
- Change "Register Forum" to "Reserve Forum"
> Chore: support USDT approval flow

- src/components/button/index.tsx
- src/hooks/useWatchTransaction.ts
- src/state/chain/atoms/transactionAtoms.ts
- src/views/auctions/auctions-sidebar/StakingVaultRevenue.tsx
> chore: add nudge button & fix staking vault revenue calcs

- src/views/governance/views/proposal-detail/ProposalHeader.tsx
> Chore: move forum link

- src/views/compare/components/RTokenCard.tsx
- src/views/overview/components/charts/APYChart.tsx
- src/views/overview/components/charts/PriceChart.tsx
- Increase RTokenCard price to 3 decimals
- Only display Rtoken apy chart and improve naming
> Feature/minor UI improvements

- src/views/issuance/index.tsx
This reverts commit 84692ac2b53ddfac58bcd2816f11fe032b415dd3.
> Revert "chore: disable zapper for arbitrum"

- src/views/governance/views/proposal/hooks/useProposalTx.ts
> chore: fix minTrade parsing

- src/views/compare/components/RegisterAbout.tsx
- src/views/home/components/About.tsx
- src/views/home/index.tsx
- src/views/staking/components/StakePosition.tsx
This pull request includes several updates to the `src/views` directory, focusing on improving the layout and conditional rendering of components. Additionally, it addresses a bug in the `StakePosition` component related to reward calculations.
* [`src/views/compare/components/RegisterAbout.tsx`](diffhunk://#diff-e1b326867380461f043828f35ddf33dc6aa616b1cf9fb78a5e4997ce3100dbcdL173-R173): Changed margin property from `my` to `mt` for better spacing control.
* [`src/views/home/components/About.tsx`](diffhunk://#diff-1ee17eb32e6b18d15f5fff92bfb5bd225c3a8a22a84144748e451bc467128e7cL31-R31): Updated `display` property to conditionally render the component based on screen size.
* [`src/views/home/index.tsx`](diffhunk://#diff-3ac70e67682aa782dd95457311e8a533c8a31eece5efc10450e3ebac2a02ed28L15-L20 …
> chore: fix layout

- src/components/feedback-button/index.tsx
- src/components/ui/button.tsx
> Chore: add feedback button on mobile

- src/state/dtf/atoms.ts
- src/utils/getExplorerLink.ts
- src/views/index-dtf/overview/components/bridge-label.tsx
- src/views/index-dtf/overview/components/index-about-overview.tsx
- src/views/index-dtf/overview/components/index-basket-overview.tsx
> Feat: add Wormwhole modal

- package-lock.json
- package.json
- src/components/token-logo/StackTokenLogo.tsx
- src/components/ui/data-table.tsx
- src/components/ui/dialog.tsx
- src/components/ui/hover-card.tsx
- src/hooks/useIndexDTFList.ts
- src/hooks/useScrollTo.ts
- src/hooks/useTokensInfo.ts
- src/views/discover/components/index/components/basket-hover-card.tsx
- src/views/discover/components/index/components/index-dtf-table.tsx
- src/views/index-dtf/overview/components/bridge-label.tsx
- src/views/index-dtf/overview/components/index-basket-overview.tsx
- src/views/index-dtf/overview/components/zap-mint/index.tsx
- src/views/index-dtf/overview/components/zap-mint/zap-details.tsx
> Feat: basket hover card

- src/views/index-dtf/overview/components/staking/index.tsx
- src/views/index-dtf/overview/components/staking/lock/submit-lock-button.tsx
> fix: exception on non checksummed address

- src/hooks/useAssetPrices.ts
- src/views/discover/components/index/components/basket-hover-card.tsx
- src/views/index-dtf/overview/components/index-governance-overview.tsx
- src/views/index-dtf/overview/hooks/use-staking-vault-apy.ts
- src/views/portfolio/rewards-updater.tsx
Basically:
```(vlDAORevenue7d / avgSupply7d) * 100 * 365 / 7```
> Feature: vlDAO APY

- src/lib/api-upload.ts
- src/views/index-dtf/manage/components/submit-button.tsx
requires https://github.com/reserve-protocol/reserve-api/pull/25
> feat: upload files to reserve-api

- src/lib/index-rebalance/check-auction.ts
- src/lib/index-rebalance/get-auctionts.ts
- src/lib/index-rebalance/numbers.ts
- src/lib/index-rebalance/open-auction.ts
- src/lib/index-rebalance/utils.ts
- src/views/index-dtf/governance/views/propose/basket/atoms.ts
This reverts commit 24f94f1dfeff50c88419fc3e79a0447fd44f1a6f.
> Revert "test: index rebalance (#665)"

- src/views/index-dtf/auctions/components/auction-item.tsx
Reverts reserve-protocol/register#693
> Revert "show 0% trade when lotsize is 0"

- src/views/index-dtf/auctions/components/auction-item.tsx
Reverts reserve-protocol/register#696
> Revert "fix fix from yesterday empty auctions"

- src/components/command-menu/index.tsx
- src/views/index-dtf/governance/components/proposal-preview/atoms.ts
- src/views/index-dtf/governance/components/proposal-preview/unknown-contract-preview.tsx
- src/views/index-dtf/governance/components/proposal-preview/use-decoded-call-datas.ts
- src/views/index-dtf/governance/components/proposal-preview/use-get-abi.ts
now: https://app.reserve.org/base/index-dtf/0xf44e6c4cd5128f48a12dde80ae7b50fff47e13cb/governance/proposal/49551724430781161449010495619900908268454848791132069564561336239845769586040
new: https://feat-unknown-abi.register-app.pages.dev/base/index-dtf/0xf44e6c4cd5128f48a12dde80ae7b50fff47e13cb/governance/proposal/49551724430781161449010495619900908268454848791132069564561336239845769586040
> Feat: fetch ABI from Etherscan for unknown contracts in governance proposals

- package-lock.json
- package.json
- src/hooks/use-zap-healthcheck.ts
- src/views/index-dtf/components/zapper/zapper-wrapper.tsx
- src/views/index-dtf/issuance/index.tsx
- src/views/index-dtf/overview/components/index-token-overview.tsx
- src/views/index-dtf/overview/components/landing-mint/index.tsx
- src/views/index-dtf/overview/components/zap-mint/index.tsx
https://github.com/reserve-protocol/react-zapper
> Chore: use react-zapper pkg

- src/views/index-dtf/auctions/views/rebalance/components/rebalance-debug.tsx
- src/views/index-dtf/auctions/views/rebalance/components/rebalance-price-impact.tsx
> chore: display price impact

- docs/specs/rebalance-v4-specification.md
- package-lock.json
- package.json
- src/views/index-dtf/auctions/views/rebalance/atoms.ts
- src/views/index-dtf/auctions/views/rebalance/components/launch-auctions-button.tsx
- src/views/index-dtf/auctions/views/rebalance/components/rebalance-debug.tsx
- src/views/index-dtf/auctions/views/rebalance/updaters/rebalance-metrics-updater.tsx
- src/views/index-dtf/auctions/views/rebalance/utils/get-rebalance-open-auction.ts
Should make it harder to accidentally target 100%
Also decrease logging from dtf-rebalance-lib
> LCAP adjustments

- src/views/index-dtf/overview/components/price-chart.tsx
> Chore: show mcap on mobile

- package-lock.json
- package.json
start rebalance with limits.low == 1 to enable arbitrarily small first rebalances for ejections
> dtf-rebalance-lib 2.4.1

- package-lock.json
- package.json
Reverts reserve-protocol/register#823
> Revert "dtf-rebalance-lib 2.4.1"
